'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class MSreplication_options
    Public Property optname As String
    Public Property value As Boolean
    Public Property major_version As Integer
    Public Property minor_version As Integer
    Public Property revision As Integer
    Public Property install_failures As Integer

End Class
