'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class masterEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=masterEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Overridable Property MSreplication_options() As DbSet(Of MSreplication_options)
    Public Overridable Property spt_fallback_db() As DbSet(Of spt_fallback_db)
    Public Overridable Property spt_fallback_dev() As DbSet(Of spt_fallback_dev)
    Public Overridable Property spt_fallback_usg() As DbSet(Of spt_fallback_usg)
    Public Overridable Property spt_monitor() As DbSet(Of spt_monitor)

End Class
