'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_monitor
    Public Property lastrun As Date
    Public Property cpu_busy As Integer
    Public Property io_busy As Integer
    Public Property idle As Integer
    Public Property pack_received As Integer
    Public Property pack_sent As Integer
    Public Property connections As Integer
    Public Property pack_errors As Integer
    Public Property total_read As Integer
    Public Property total_write As Integer
    Public Property total_errors As Integer

End Class
