'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_fallback_dev
    Public Property xserver_name As String
    Public Property xdttm_ins As Date
    Public Property xdttm_last_ins_upd As Date
    Public Property xfallback_low As Nullable(Of Integer)
    Public Property xfallback_drive As String
    Public Property low As Integer
    Public Property high As Integer
    Public Property status As Short
    Public Property name As String
    Public Property phyname As String

End Class
