'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class spt_fallback_usg
    Public Property xserver_name As String
    Public Property xdttm_ins As Date
    Public Property xdttm_last_ins_upd As Date
    Public Property xfallback_vstart As Nullable(Of Integer)
    Public Property dbid As Short
    Public Property segmap As Integer
    Public Property lstart As Integer
    Public Property sizepg As Integer
    Public Property vstart As Integer

End Class
